### ISSUE TITLE
Add a "Favourites" function

### ISSUE THREAD

**Issue by milindalvares** [Deepak-1373/Movie-Search-App#1]
Feature description:
It would be great to be able to ❤️ movies which we want to reference later.

Technical challenges:
- Store the favourites list in memory or local storage. It's fine if the list is lost every time you reload the page since you don't control the API, but would be nice if local storage was used to persist the data.
- Allow ranking the favourites higher or lower.
- Use favourites to suggest "Other movies you might like" based on criteria like most popular genre, actors, etc.
- Bonus points for using tailwindcss 

Things we'd like to see:
- Precise commit messages. Not just a commit dump at the end of building the feature. We'd like to see a progression of commits and then refactors as you refine the feature.
- Scope out what part of the feature request you want to build out. The challenges are a suggestion, so figure out the scope of work that you can handle within a time frame and work on just that.
- Put care into semantics, formatting, and making sure your functions and components are refactored to be reusable. This is a test of programming skills, not product building!

**Comment by Deepak-1373** [comment]
I have completed the challenge and merged the changed code to the main branch. Please let me know if you have any questions.
